apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: banias-frontend # The name of the app
  namespace: default # The namespace the app will use
  labels:
    knative.dev/type: "app"
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            #TODO
            image: gcr.io/my-project/banias-frontend:latest # The URL to the image of the app
            volumeMounts:
            - name: google-cloud-key
              readOnly: true
              mountPath: /var/secrets/google
            ports:
              - containerPort: 8081
            env:
            - name: "BANIAS_PROJECTID"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_PROJECTID"
                  name: "banias-frontend-config"
            - name: "BANIAS_DEBUG"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_DEBUG"
                  name: "banias-frontend-config"
            - name: "BANIAS_TOPIC"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_TOPIC"
                  name: "banias-frontend-config"
            - name: "BANIAS_PORT"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_PORT"
                  name: "banias-frontend-config"
            - name: "BANIAS_METRICSPORT"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_METRICSPORT"
                  name: "banias-frontend-config"
            - name: "BANIAS_PUBSUBMAXBATCH"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_PUBSUBMAXBATCH"
                  name: "banias-frontend-config"
            - name: "BANIAS_PUBSUBAGGRIGATORS"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_PUBSUBAGGRIGATORS"
                  name: "banias-frontend-config"
            - name: "BANIAS_PUBSUBMAXPUBLISHDELAY"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_PUBSUBMAXPUBLISHDELAY"
                  name: "banias-frontend-config"
            - name: "BANIAS_MAXPUBSUBGOROUTINESAMOUNT"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_MAXPUBSUBGOROUTINESAMOUNT"
                  name: "banias-frontend-config"
            - name: "BANIAS_MAXPUBSUBGOROUTINEIDLEDURATION"
              valueFrom:
                configMapKeyRef:
                  key: "BANIAS_MAXPUBSUBGOROUTINEIDLEDURATION"
                  name: "banias-frontend-config"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            imagePullPolicy: Always
          volumes:
            - name: google-cloud-key
              secret:
                secretName: pubsub-key

